dubbo:
  scan:
    base-packages: com.study.wzf.mydubbouser.controller
  application:
    name: mydubbo-user
    owner: wzf
  registry:
    address: zookeeper://172.16.2.106:2181?172.16.2.182:2181,172.16.2.98:2181
    check: false
    group: mydubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://172.16.2.106:2181?172.16.2.182:2181,172.16.2.98:2181
    retry-times: 30
    cycle-report: false
    group: mydubbo-dev



