dubbo:
  scan:
    base-packages: com.study.wzf.myuserprovider.service
  application:
    name: myuser-service
    owner: wzf
  protocol:
    port: 20880
    name: dubbo
    #host:
  registry:
    address: zookeeper://172.16.2.106:2181
    timeout: 50000
    check: true
    simplified: true
    group: mydubbo-dev
  metadata-report:
    address: zookeeper://172.16.2.106:2181
    cycle-report: false
    retry-times: 30
    group: mydobbo-dev

